// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqzxdlhytybpkfouehyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xenhkbGh5dHlicGtmb3VlaHluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5Njg5NDksImV4cCI6MjA2OTU0NDk0OX0.XnlD62SzLqWwrgGlLlecyj-6k5XqAmAdiPDbF1mPDaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});